== Expose your data using OpenAPI and Teiid

If you want expose your data using OpenAPI, now you have one more alternative using Teiid with out writing any code and entirely implement the API layer using SQL/DDL.

This guide walks you through the process of building an application that uses Teiid Spring Boot to expose OpenAPI
interface on relational database. Please note that you can easily extend the same concept to *any* data sources, like
flat files, excel files, MongoDB etc. that are supported by Teiid's translator eco-system. 

Before you start, have your OpenAPI metadata document available. If you want to build a new API document, you can use tools like link:https://www.apicur.io/[APICurio] and build your API document. Typically this file is named as `openapi.json`. For this example we are going to use the OpenAPI example link:https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml[Pet Store]


=== What you’ll build

You’ll build an application that exposes a OpenAPI interface on a embedded H2 database. The init scripts for this 
embedded database are also included in this example. When you finished, you should be able to issue a call to 
http://localhost:8080/swagger-ui.html and see the Swagger UI for the implemented service.

=== What you’ll need

* About 10 minutes
* A favorite text editor or IDE
* JDK 1.8 or later
* Maven 3.0+
* OpenAPI Document (link:https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml[Pet Store])


=== Build With Maven
First you set up a basic build script. You can use any build system you like when building apps with Spring, but the code you need to work with Maven is included here. If you’re not familiar with Maven, refer to link:https://spring.io/guides/gs/maven[Building Java Projects with Maven].

Go to link:http://start.spring.io/[Spring Initializer] and type in "JDBC" in dependencies and generate a project. Then open the generated code in your favorite IDE, and edit the pom.xml to add the below dependencies.

Otherwise, in a project directory of your choosing, create the following sub-directory structure; for example, with

----
mkdir -p src/main/java/example on *nix systems:
----

and create pom.xml file of your choosing and add following maven dependencies

[source,xml]
.*teiid-spring-boot-starter, spring-openapi*
----
<dependency>
   <groupId>org.teiid</groupId>
   <artifactId>teiid-spring-boot-starter</artifactId>
   <version>${project.version}</version>
</dependency>
<dependency>
    <groupId>org.teiid</groupId>
    <artifactId>spring-openapi</artifactId>
    <version>${project.version}</version>
</dependency> 
----

Since we are going to connect H2 database, add the JDBC driver dependency. You can replace this with database driver of your choosing.
[source,xml]
.*h2*
----
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <scope>runtime</scope>
</dependency>
----

This example makes use of code generation techniques on given `openapi.json` document, to enable that Teiid provides a Maven plug-in. Add the following fragment to your `pom.xml` file under 

[source,xml]
.*Code Generation maven plugin*
----
  <build>
    <plugins>
      <plugin>
        <groupId>org.teiid</groupId>
        <artifactId>vdb-codegen-plugin</artifactId>
        <version>${project.version}</version>
        <configuration>
          <packageName>org.teiid.spring.example</packageName>
          <generateApplicationClass>false</generateApplicationClass>
          <generateDataSourceClasses>false</generateDataSourceClasses>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>vdb-codegen</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
----

This plugin searches for a Virtual Database with name `teiid-vdb.ddl` and OpenAPI document with name `openapi.json` in the `resources` directory by default. If the names do not match your configuration you can configure the alternative names on above plug-in.

=== Define Virtual Database
To support the (link:https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml[Pet Store]) API, the following VDB needs to be defined. This needs to stored in `src/main/resources` directory with name `teiid-vdb.ddl`

[source,sql]
.*Virtual Database*
----

CREATE DATABASE openapi OPTIONS (ANNOTATION 'PetStore VDB');
USE DATABASE PetStore;

SET NAMESPACE 'http://teiid.org/rest' AS REST;
CREATE FOREIGN DATA WRAPPER h2;
CREATE SERVER mydb TYPE 'NONE' FOREIGN DATA WRAPPER h2;

CREATE VIRTUAL SCHEMA pets;
CREATE SCHEMA petdb SERVER mydb;

-- H2 converts the schema name to capital case
IMPORT FOREIGN SCHEMA PETSTORE FROM SERVER mydb INTO petdb OPTIONS("importer.useFullSchemaName" 'false');

SET SCHEMA pets;

CREATE VIRTUAL PROCEDURE createPets(IN body json) OPTIONS (UPDATECOUNT 1)AS
BEGIN  
   LOOP ON (SELECT j.id, j.name, j.status FROM JSONTABLE(body, '$', false COLUMNS id integer, name string, status string) as j) AS x
   BEGIN
       INSERT INTO petdb.Pet(id, name, status) VALUES (x.id, x.name, x.status);
   END
END

CREATE VIRTUAL PROCEDURE showPetById(IN petId integer) RETURNS json OPTIONS (UPDATECOUNT 0)AS
BEGIN
    declare json x = (SELECT JSONOBJECT(id, name, status) FROM petdb.Pet where id = petId);
    return x;
END

CREATE VIRTUAL PROCEDURE listPets(IN "limit" integer) RETURNS json OPTIONS (UPDATECOUNT 0)AS
BEGIN
    declare json x = (SELECT JSONARRAY_AGG(JSONOBJECT(p.id, p.name, p.status)) 
        FROM petdb.Pet p WHERE p.status in (status));
    return x;
END

----

NOTE: The `operationId` field of every API call becomes a Virtual Procedure name. Then this procedure needs to have ALL the Request, Path, Header and Body based parameters on it. The names MUST match exactly to OpenAPI document. Try to match the data types of the parameters to that of Teiid's data types. Then return type should also match, mostly if you are returning JSON content it will be `json` type. If you need to return an error condition you can use `RAISE SQLEXCEPTION` in the stored procedure with proper Http Status code, which will be converted automatically into a correct response.

=== Define the Data Sources
For accessing the database, we need to configure data source. (This file can also be generated automatically)

[source,java]
.*src/main/java/org/example/DataSources.java*
----
package org.example;

@Configuration
public class DataSources {
    @ConfigurationProperties(prefix = "spring.datasource.mydb")
    @Bean
    public DataSource mydb() {
        return DataSourceBuilder.create().build();
    }
}
----

We are creating one data source connection, with name "mydb". Now we need to provide the corresponding configuration for this data sources. In "application.properties" file, define *your* configuration similar to

[source,text]
.*src/main/resources/application.properties*
----
spring.datasource.mydb.jdbc-url=jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS petstore
spring.datasource.mydb.username=sa
spring.datasource.mydb.password=sa
spring.datasource.mydb.driver-class-name=org.h2.Driver
spring.datasource.mydb.platform=mydb
----

Change the property values above to fit your database environment. The property with "importer.SchemaPattern" post fix defines that database schema that you would like to access tables from. There lot more properties to restrict/allow what schema objects you want to work with. Check Teiid documentation for Translator "import" properties.

property "spring.datasource.mydb.platform" defines the prefix for the init scripts for your database, data-${platform}.sql and schema-${platform}.sql. Also disable hibernate to generate any hb2ddl scripts. 

=== Create an Application class

Here you create an Application class with all the components.

[source,java]
.src/main/java/org/example/Application.java
----
package org.example;

@SpringBootApplication
public class Application {    
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args).close();
    }
}
----

Now build using maven
----
mvn clean install
----

and run the application

----
java -jar target/example-1.0.0-SNAPSHOT.jar
----

==== That's it, You are done exposing the Data Source with OpenAPI

Once you execute this application, Teiid Spring Boot will connect to the data source configured and expose a OpenAPI rest interface using the Spring Boot's built in web engine. You can issue a call to swagger-ui using the URL below.

---
http://localhost:8080/swagger-ui.html
---
     
That's it you have successfully implemented OpenAPI interface using a Teiid's Virtual database. Since Teiid supports various data sources, you can expose this API on any data source. For full support of all the data sources supported checkout Teiid documentation on at link:http://teiid.io[Teiid.io]
