
= Teiid Spring Boot User Guide
:toc: manual
:toc-placement: preamble

This is document is for how to use `teiid-spring-boot-starter` run teiid with SpringApplication.

== Application Development

This section contains the steps to develop a maven based Teiid Spring Boot Application.

=== Prepare pom.xml

Maven dependencies and Maven Plugins are 2 prerequisites need to set down correctly in a pom.xml:

1. <<Maven dependencies, Maven dependencies>>
2. <<Maven Plugins, Maven Plugins>> 

==== Maven dependencies 

[source,xml]
.*teiid-spring-boot-starter - (Mandatory)*
----
<dependency>
   <groupId>org.teiid</groupId>
   <artifactId>teiid-spring-boot-starter</artifactId>
</dependency>
----

[source,xml]
.*teiid connectors - (Optional, depend on what you use)*
----
<dependency>
   <groupId>org.jboss.teiid.connectors</groupId>
   <artifactId>translator-X</artifactId>
</dependency>
<dependency>
   <groupId>org.jboss.teiid.connectors</groupId>
   <artifactId>connector-X</artifactId>
</dependency>
----

[source,xml]
.*thirdparty - (Optional, depend on what you use)*
----
<dependency>
   <groupId>X.Y.Z</groupId>
   <artifactId>X</artifactId>
</dependency>
----

==== Maven Plugins

[source,xml]
.*spring-boot-maven-plugin - (Mandatory)*
----
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <version>${spring-boot.version}</version>
    <executions>
        <execution>
            <goals>
                <goal>repackage</goal>
            </goals>
        </execution>
    </executions>
</plugin>
----

NOTE: `spring-boot-maven-plugin` are used to package runnable jar.

=== The main() method class Development

[source,java]
.The skeleton Spring boot main() method class
----
@SpringBootApplication
public class Main {

    public static void main(String[] args) {
        SpringApplication.run(Main.class, args);
    }
}
----

With the skeleton of the Spring boot main() method class, a series of bean entities listed as following, which need to be injected via @Bean annotation.

.*Configuration Beans*
|===
|*Type* |*Name* |*Optional* |*Notes*

|org.teiid.runtime.EmbeddedConfiguration
|embeddedConfiguration
|true
|If embeddedConfiguration not injected, an EmbeddedConfiguration will be initialized with default settings.

|org.teiid.transport.SocketConfiguration
|socketConfiguration
|true
|If socketConfiguration not injected, a SocketConfiguration will be initialized with 0.0.0.0 as bind address, 31000 as port number.

|Integer
|port
|true
|Used to control transport bind port number, the default is 3100

|javax.transaction.TransactionManager
|transactionManager
|true
|Refer to <<Appendix I: Example of TransactionManager Bean, Appendix I: Example of TransactionManager Bean>> for a example of TransactionManager injection

|String
|securityDomain
|true
|The default security domain is `teiid-security`, should match the jaas security policy setting which used in teiid securityHelper implementation.  

|org.teiid.security.SecurityHelper
|securityHelper
|true
|Refer to https://teiid.gitbooks.io/documents/content/embedded/Secure_Embedded_with_PicketBox.html[Secure Embedded with PicketBox] to implement a SecurityHelper

|===

.*Connector Beans*
|===
|*Type* |*Name* |*Optional* |*Notes*

|Map<String, DataSource>
|datasources
|true
|To inject the datasources which used by teiid, the key is `connection-jndi-name` in VDB, <<Appendix II - Register Map<String, DataSource> Bean, Appendix II - Register Map<String, DataSource> Bean>> is a example for registering DataSource with Map<String, DataSource> Bean

|Map<String, ConnectionFactory>
|connectionFactories
|true
|To inject the connectionFactories which used by teiid, the key is `connection-jndi-name` in VDB, <<Appendix III - Register Map<String, ConnectionFactory> Bean, Appendix III - Register Map<String, ConnectionFactory> Bean>> is a example for registering ConnectionFactory with Map<String, ConnectionFactory> Bean

|Set<String>
|connectionFactoryNames
|true
|To inject a set of connectionFactory names, each names referenced with `connection-jndi-name` in VDB and should have a relevant DataSource/ConnectionFactory Bean in Configuration.

|DataSource
|datasource
|true
|The datasource reference with the name in connectionFactoryNames, <<Appendix IV - Register DataSource Bean, Appendix IV - Register DataSource Bean>> is a example for registering dataSource and connectionFactoryNames Bean

|ConnectionFactory
|connectionFactory
|true
|The connectionFactory reference with the name in connectionFactoryNames, <<Appendix V - Register ConnectionFactory Bean, Appendix V - Register ConnectionFactory Bean>> is a example for registering connectionFactory and connectionFactoryNames Bean

|Map<String, ExecutionFactory<?, ?>> 
|translators
|true
|To register translators which used by teiid, the key is `translator-name` in VDB, refer to <<Translators Registration>> for details.

|===

=== VDB Deployment

VDB can be deployed either via a `.xml` file, or `.sql` file. Refer to https://teiid.gitbooks.io/documents/content/reference/vdb_guide.html[Virtual Databases] for more detaila about VDB.

The `.xml`/`.sql` file can either be packaged in the classpath of Spring Boot Runnable jar, or placed in the file system, the external .yml configuration can be used to configure the path of file.

[source,yml]
.*Example of .yml controlled deployment*
----
teiid:
  vdbs: 
    path/to/portfolio-vdb.xml
  ddls:
    account.sql
----

Note that, with above .yml configuration, Spring Boot will first find the `path/to/portfolio-vdb.xml`/`account.sql` from classpath, if not exist, then find from file system.

Alternatively, the `.xml`/`.sql` can be passed from command line:

[source,java]
.*Example of commands deployment*
----
java -jar SAMPLE.jar path/to/portfolio-vdb.xml, account.sql
----

The same as yml controlled deployment, Spring Boot will first find the `path/to/portfolio-vdb.xml`/`account.sql` from classpath, if not exist, then find from file system.

=== Configuration

Teiid Spring Boot Starter compatible with all other starter's YML Configuration, like datasource, resource adapters, etc. The following are teiid added:

|===
|*Name* |*Pattern* |*Description* 

|teiid.translators
|comma separate list
|Use to filter the translators auto-detection 

|teiid.vdbs
|comma separate list
|Use to set the path of -vdb.xml

|teiid.ddls
|comma separate list
|Use to set the path of ddl sql

|===

[source,yml]
.*An example .yml*
----
spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

teiid:
  translators: 
    h2,file
  vdbs:
    path/to/portfolio-vdb.xml
  ddls:
    account.sql
----

== Translators Registration

Basicly, there are 2 ways to register Teiid Translators, implicit registration and explicit registration.

=== Implicit

The implicit registration is way of auto-detect and registering, if the translator class and referenced Resource Adpater/Driver library are in classpath, then this translator will be initialized, started and registered to Teiid EmbeddedServer.

If the explicit way be used, the implicit registration will not take place. A external configuration can be used to filter and manually set which translator can be registered implicitly. Refer to <<Configuration, Configuration>> for details abouot how to filter translator auto-detection.

[source,yml]
.*Example of external .yml to filter translator*
----
teiid:
  translators:
    h2,file
----

NOTE: The implicit registration with a external .yml configuration is recommend way.

=== Explicit

The explicit registration are no difference with register DataSource or ConnectionFactory, <<Appendix VI - Register translators Bean, Appendix VI - Register translators Bean>> for an example of explicit registering translators.

== Available Examples

|===
|*Name* |*Features Demonstrated* |*Description* |*Prerequisites*

|link:teiid-spring-boot-samples/teiid-spring-boot-sample-datafederation/README.adoc[vdb-datafederation]
|Data Federation, TEXTTABLE, Native Query, JDBC translator, File Translator, 
|Shows how to expose multiple data sources for data federation
|None

|link:teiid-spring-boot-samples/teiid-spring-boot-sample-loopback/README.adoc[loopback-source]
|Loopback Translator, Query
|Shows how to use teiid loopback translator and use Teiid Spring Boot Starter to setup a teiid runtime environment
|None

|link:teiid-spring-boot-samples/teiid-spring-boot-sample-empty/README.adoc[empty-source]
|Teiid Spring Boot Starter
|Shows how to use Teiid Spring Boot Starter to setup a teiid runtime environment
|None
|===


== Appendix I: Example of TransactionManager Bean

[source,java]
----
@Bean
public TransactionManager transactionManager() {
    return  EmbeddedHelper.Factory.transactionManager(c -> c.coreEnvironmentBean(core -> {
        core.setSocketProcessIdPort(0);
        core.setSocketProcessIdMaxPorts(10);
    }).coordinatorEnvironmentBean(coordinator -> {
        coordinator.setEnableStatistics(false);
        coordinator.setDefaultTimeout(300);
        coordinator.setTransactionStatusManagerEnable(false);
        coordinator.setTxReaperCancelFailWaitPeriod(120000);
    }).objectStoreEnvironmentBean(objectStore -> {
        objectStore.setObjectStoreDir(System.getProperty("java.io.tmpdir") + "/narayana");
    }));
}
----

== Appendix II - Register Map<String, DataSource> Bean

[source,java]
----
@Bean
public Map<String, DataSource> datasources() throws ResourceException {
        
    Map<String, DataSource> datasources = new HashMap<>(1); 
    DataSource ds = EmbeddedHelper.Factory.newDataSource(c -> c.localManagedConnectionFactory(mcf -> {
        mcf.setDriverClass("org.h2.Driver");
        mcf.setConnectionURL(URL);
        mcf.setUserName("sa");
        mcf.setPassword("sa");
    }).poolConfiguration(p -> {
        p.setMaxSize(30);
        p.setMinSize(5);
        p.setBlockingTimeout(30000);
        p.setIdleTimeoutMinutes(10);
    }));
        
    datasources.put("accounts-ds", ds);
    return datasources;
}
----

== Appendix III - Register Map<String, ConnectionFactory> Bean

[source,java]
----
@Bean
public Map<String, ConnectionFactory> marketData() throws ResourceException {
    Map<String, ConnectionFactory> factories = new HashMap<>();
    ConnectionFactory cf = EmbeddedHelper.Factory.fileConnectionFactory(mcf -> {
        mcf.setParentDirectory(marketdataDir);
        mcf.setAllowParentPaths(true);
    });
    factories.put("marketdata-file", cf);
    return factories;
}
----

== Appendix IV - Register DataSource Bean

[source,java]
----
@Bean
public Set<String> connectionFactoryNames() {
    Set<String> names = new HashSet<>();
    names.add("account-ds");
    return names;
}

@ConfigurationProperties(prefix = "spring.datasource.postgres")
@Bean(name = "account-ds")
@Primary
public DataSource dataSource() {
    return DataSourceBuilder.create().build();
}
----

== Appendix V - Register ConnectionFactory Bean

[source,java]

----
@Bean
public Set<String> connectionFactoryNames() {
    Set<String> names = new HashSet<>();
    names.add("marketdata-file");
    return names;
}

@Bean(name = "marketdata-file")
public ConnectionFactory marketData() throws ResourceException {
    return EmbeddedHelper.Factory.fileConnectionFactory(mcf -> {
        mcf.setParentDirectory(marketdataDir);
        mcf.setAllowParentPaths(true);
    });
}
----

== Appendix VI - Register translators Bean

[source,java]
----
@Bean
public Map<String, ExecutionFactory<?, ?>> translators() throws TranslatorException {
    Map<String, ExecutionFactory<?, ?>> factories = new HashMap<>();
    H2ExecutionFactory h2 = new H2ExecutionFactory() ;
    h2.start();
    FileExecutionFactory file = new FileExecutionFactory();
    file.start();
    factories.put("h2", h2);
    factories.put("file", file);
    return factories;
}
---- 
