CREATE DATABASE customer;
USE DATABASE customer;

CREATE FOREIGN DATA WRAPPER fake;
CREATE FOREIGN DATA WRAPPER fakeSource TYPE fake;
CREATE SERVER fakeSource FOREIGN DATA WRAPPER fakeSource;
CREATE SERVER fakeSource2 FOREIGN DATA WRAPPER fake;

CREATE SCHEMA accounts SERVER fakeSource;
CREATE SCHEMA accounts1 SERVER fakeSource2;

IMPORT FROM SERVER fakeSource INTO accounts;
IMPORT FROM SERVER fakeSource2 INTO accounts1;
