CREATE DATABASE foo;
USE DATABASE foo;

CREATE FOREIGN DATA WRAPPER h2;
CREATE SERVER mydb TYPE 'NONE' FOREIGN DATA WRAPPER h2 OPTIONS ("resource-name" 'mydb');

CREATE SCHEMA foo SERVER mydb;
SET SCHEMA foo;

CREATE FOREIGN TABLE FOO(name string, id integer);
