CREATE DATABASE foo;
USE DATABASE foo;

CREATE FOREIGN DATA WRAPPER h2;
CREATE SERVER mydb FOREIGN DATA WRAPPER h2;

CREATE SCHEMA foo SERVER mydb;
SET SCHEMA foo;

CREATE FOREIGN TABLE FOO(name string, id integer);
