CREATE DATABASE customer OPTIONS (ANNOTATION 'Customer VDB');
USE DATABASE customer;

CREATE FOREIGN DATA WRAPPER h2;
CREATE SERVER mydb TYPE 'NONE' FOREIGN DATA WRAPPER h2 OPTIONS ("resource-name" 'mydb');
CREATE VIRTUAL SCHEMA virt;
CREATE SCHEMA accounts SERVER mydb;

SET SCHEMA accounts;

IMPORT FOREIGN SCHEMA MYSCHEMA FROM SERVER mydb INTO accounts OPTIONS("importer.useFullSchemaName" 'false');

IMPORT DATABASE FOO VERSION '1';
IMPORT DATABASE BAR VERSION '1';
