apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: dv-customer
spec:
  replicas: 1
  expose:
    - LoadBalancer
  datasources:
    - name: sampledb
      type: postgresql
      properties:
        - name: username
          value: postgres
        - name: password
          value: postgres
        - name: jdbc-url
          value: jdbc:postgresql://database/postgres
  build:
    source:
      mavenRepositories:
        repo-04-indy: http://indy.psi.redhat.com/browse/maven/group/builds-untested/
      ddl: |
        CREATE DATABASE customer OPTIONS (ANNOTATION 'Customer VDB');
        USE DATABASE customer;

        CREATE SERVER sampledb TYPE 'NONE' FOREIGN DATA WRAPPER postgresql;

        CREATE SCHEMA accounts SERVER sampledb;
        CREATE VIRTUAL SCHEMA portfolio;

        SET SCHEMA accounts;
        IMPORT FOREIGN SCHEMA public FROM SERVER sampledb INTO accounts OPTIONS("importer.useFullSchemaName" 'false');

        SET SCHEMA portfolio;

        CREATE VIEW CustomerZip(id bigint PRIMARY KEY, name string, ssn string, zip string) AS 
            SELECT c.ID as id, c.NAME as name, c.SSN as ssn, a.ZIP as zip 
            FROM accounts.CUSTOMER c LEFT OUTER JOIN accounts.ADDRESS a 
            ON c.ID = a.CUSTOMER_ID;
